# HTTP → HTTPS redirect
server {
    listen 80;
    server_name ~^(?<project>.+)\.p82\.test$;

    return 301 https://$host$request_uri;
}

# HTTPS
server {
    listen 443 ssl;
    server_name ~^(?<project>.+)\.p82\.test$;

    ssl_certificate /etc/nginx/ssl/_wildcard.pxx.test.pem;
    ssl_certificate_key /etc/nginx/ssl/_wildcard.pxx.test-key.pem;

    root /var/www/p82/$project;
    index index.php index.html;
    location ^~ /ret_core_v3/assets/ {
        alias /var/www/p82/ret_core_v3/assets/;
        access_log off;
        expires 7d;
    }

    location / {
        try_files /public$uri /public$uri/ $uri $uri/ @front_controller;
    }

    location @front_controller {
        if (-f $document_root/public/index.php) {
            rewrite ^ /public/index.php last;
        }

        rewrite ^ /index.php last;
    }

    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_pass php82:9000;
        fastcgi_param SCRIPT_FILENAME $request_filename;
    }
}
